### ISSUE TITLE
Home page ("Testimonials" section)

### ISSUE THREAD

**Issue by ekaterinapeter** [yaeru/fas#11]
As mentioned on TG:  adding a small section on the current homepage (not yet publish) with client and partner references? Just put as empty ones for now so we fill it in by ourselves. It should be between "Why FAS" and "Featured News and reports" sections". 
can be as simple as on this page https://www.hashcashconsultants.com/

**Comment by ekaterinapeter** [comment]
![Uploading Screen Shot 2020-11-03 at 2.26.16 PM.png…]()

**Comment by yaeru** [comment]
@ekaterinapeter please add the image correctly, you push send comment before is already uploaded
