### ISSUE TITLE
FAS homepage services 

### ISSUE THREAD

**Issue by ekaterinapeter** [yaeru/fas#12]
Hi @yaeru ! Happy to see the homepage updated, tho I've noticed that the part of the advisory services is being placed in a different way than fundraising, kind of closer to the icon then the previous section
<img width="456" alt="Screen Shot 2020-11-05 at 1 51 01 PM" src="https://user-images.githubusercontent.com/70971138/98232028-35898280-1f6e-11eb-977c-1141ce508ba2.png">

**Comment by yaeru** [comment]
Fixed
