### ISSUE TITLE
Website mobile version

### ISSUE THREAD

**Issue by yaeru** [yaeru/fas#2]
As for now, the website designs are not adjusted to the mobile version. We would need this to be improved as well.

**Comment by yaeru** [comment]
@ekaterinapeter you refer to the actual pages of the new ones that I created?

**Comment by ekaterinapeter** [comment]
I refer to the overall website design with actual and new pages created.  Here is what I mean:
<img width="557" alt="Screen Shot 2020-09-23 at 5 57 50 PM" src="https://user-images.githubusercontent.com/70971138/94030435-7b2b2b00-fdc6-11ea-8ec1-f2b5705e4588.png">
<img width="502" alt="Screen Shot 2020-09-23 at 5 58 08 PM" src="https://user-images.githubusercontent.com/70971138/94030441-7cf4ee80-fdc6-11ea-87bf-7bc712425953.png">

Please let me know if it was within the scope of your agreement with Elena.
