### ISSUE TITLE
News & Reports page

### ISSUE THREAD

**Issue by yaeru** [yaeru/fas#6]
we would need to add categorization and search function as well as make report icons smaller and overall the page easier to navigate.
Here are some examples from competitors that I liked https://www.dashdevs.com/blog/ (in terms of design and structure), https://media.hashcashconsultants.com/ (in terms of structure, not the design).
Let me know if I need to create categories for the content or organize it somehow for you to make the set up.

**Comment by yaeru** [comment]
@ekaterinapeter ok!

**Comment by ekaterinapeter** [comment]
thanks! We also noticed that during the transfer from our old website the content design got some issues and now older reports look out of the overall style, example https://www.fintech-advisory.com/news/blockchainbanana
Would it be also possible to include in the scope of work for this section?

**Comment by yaeru** [comment]
I added the search, but the template does not allow change the layout of archives


> We also noticed that during the transfer from our old website the content design got some issues and now older reports look out of the overall style,

It depends on the note, in some they added custom content, but I tried to normalize the sizes of the texts
![image](https://user-images.githubusercontent.com/8006634/96177407-3a758c00-0f04-11eb-80e5-c2acd23b1a22.png)
