### ISSUE TITLE
FAS homepage

### ISSUE THREAD

**Issue by yaeru** [yaeru/fas#8]
1) Services right next to the png can have a bigger font, bigger bullet point, or maybe a separate png instead of a bullet point 
2) Instead of the FAS description on the homepage, we would like to add "Why us?" section and design each bullet point with a png https://prnt.sc/uhuuev

![image](https://user-images.githubusercontent.com/8006634/93256688-13dffc00-f772-11ea-8f30-247618a623dc.png)

**Comment by yaeru** [comment]
@ekaterinapeter no problem

1. this is in figma o the actual homepage?
2. please pass me the list redacted

**Comment by ekaterinapeter** [comment]
Hi @yaeru 
1)not sure I understand the 1st question but if you mean the first comment - I mentioned it based on Fir=gma design as there is no new homepage design available for me now (if it is ok on the actual homepage then forget it)
2) here is the written content:

Why FAS? 
- Expertise in Fintech and Blockchain
- Global presence and understanding of local markets
-  Experience in South Korea, China, Latin America, Europe, Russia
-  Understanding of business processes from early development till the growth stage
- On-ground experience and mobility
-  Diversified network of professionals and business connections
-  Quick response and assistance 
- Established connections in multiple markets





> @ekaterinapeter no problem
> 
> 1. this is in figma o the actual homepage?
> 2. please pass me the list redacted

**Comment by yaeru** [comment]
@ekaterinapeter  Te text in the point 1 refer to your comment:
> Services right next to the png can have a bigger font, bigger bullet point, or maybe a separate png instead of a bullet point

I wasn't sure if you mean change the layout of the listing as it looked in figma or how it was on the web.

This Why FAS list in which part of the home do you want it? that is not clear to me.

**Comment by ekaterinapeter** [comment]
@yaeru it can be instead What is FAS section 
![Uploading Screen Shot 2020-11-05 at 1.49.19 PM.png…]()

**Comment by yaeru** [comment]
@ekaterinapeter please add the image correctly, you push send comment before is already uploaded

**Comment by yaeru** [comment]
@ekaterinapeter but the "What is FAS" section does not exist, where is it?

**Comment by ekaterinapeter** [comment]
<img width="1277" alt="Screen Shot 2020-11-06 at 3 41 50 PM" src="https://user-images.githubusercontent.com/70971138/98367410-9f755b00-2046-11eb-8ec9-3c2f05d0cac4.png">

**Comment by ekaterinapeter** [comment]
Sorry, attached the screenshot correctly. This is WHat is FAS section

**Comment by yaeru** [comment]
Allready on the home, its ready?
